---

# Main collection of env. vars to set for all tasks and scripts.
env:
    # Name of the ultimate destination branch for this CI run, PR or post-merge.
    DEST_BRANCH: "master"
    # Shell used to execute all script commands
    CIRRUS_SHELL: "/bin/bash"
    # No need to go crazy, but grab enough to cover most PRs
    CIRRUS_CLONE_DEPTH: 50
    # Unique suffix label to use for all images produced by _this_ run (build)
    IMG_SFX: "${CIRRUS_BUILD_ID}"
    # Google Application Credentials (JSON) with access to create
    # Note: Actual authZ specified by service-account roles.
    # Ref: https://cloud.google.com/compute/docs/access/service-accounts?&_ga=2.102552833.-1670000616.1540407237#accesscopesiam
    GAC_JSON: ENCRYPTED[7fba7fb26ab568ae39f799ab58a476123206576b0135b3d1019117c6d682391370c801e149f29324ff4b50133012aed9]


gcp_credentials: ENCRYPTED[823fdbc2fee3c27fa054ba1e9cfca084829b5e71572f1703a28e0746b1a924ee5860193f931adce197d40bf89e7027fe]

timeout_in: 60m

task:
    name: "Validate"
    alias: "validate"
    timeout_in: 5m
    container: &ci_container
        # Ref: https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment
        dockerfile: "ci/Containerfile"
        cpu: 1
        memory: "1G"
    script:
        - "ci/shellcheck.sh"
        - "make image_builder/gce.json"
        - "make base_images/gce.json"


task:
    name: "Image-builder image"
    alias: "image_builder"
    # Usable images are produced from PRs, not merges.
    only_if: $CIRRUS_PR =~ '.+'
    depends_on:
        - validate
    # Packer needs time to clean up partially created VM images
    auto_cancellation: $CI != "true"
    timeout_in: 30m
    container:
      dockerfile: "image_builder/Containerfile"
      cpu: 2
      memory: "2G"
    script: "ci/make_image_builder.sh"
    manifest_artifacts:
        path: image_builder/manifest.json
        type: application/json


task:
    alias: "podman_containers"
    depends_on:
        - image_builder
    only_if: $CIRRUS_PR =~ '.+'
    timeout_in: 30m
    gce_instance: &ibi_vm
        image_project: "libpod-218412"
        image_name: "image-builder-${IMG_SFX}"
        zone: "us-central1-a"
        disk: 200  # Must be 200, negatively affects performance otherwise.
    matrix:
        - name: &name "${DISTRO_NAME}_podman container"
          env:
            DISTRO_NAME: 'fedora'
            # Add a 'c' to the tag for consistency with VM Image names
            DEST_FQIN: &fqin 'quay.io/libpod/${DISTRO_NAME}_podman:c$IMG_SFX'
        - name: *name
          env:
            DISTRO_NAME: 'prior-fedora'
            DEST_FQIN: *fqin
        - name: *name
          env:
            DISTRO_NAME: 'ubuntu'
            DEST_FQIN: *fqin
        - name: *name
          env:
            DISTRO_NAME: 'prior-ubuntu'
            DEST_FQIN: *fqin
    env:
        TEMPDIR: '$CIRRUS_WORKING_DIR'
        _LOGIN_CMD: ENCRYPTED[d15806d68c90cf74faca59bc4f81ada269538092b8449c7d8cd4cf44cd8d58a7482d2b249a9da06508f32f9e4075dc18]
    script:
        - 'make ${DISTRO_NAME}_podman'
        - ' ${_LOGIN_CMD}'  # Keep this out of command-history
        - 'trap "podman logout --all" EXIT INT STOP CONT'
        - 'podman tag ${DISTRO_NAME}_podman:$IMG_SFX $DEST_FQIN'
        - 'podman push $DEST_FQIN'
    container_artifacts:
        path: '*.tar'
        type: 'application/x-tar'


task:
    alias: "base_images"
    only_if: $CIRRUS_PR =~ '.+'
    depends_on:
        - image_builder
    # Packer needs time to clean up partially created VM images
    auto_cancellation: $CI != "true"
    timeout_in: 30m
    # Cannot use a container for this task, virt required for fedora image conversion
    gce_instance:
        <<: *ibi_vm
        # Nested-virt is required, need Intel Haswell or better CPU
        enable_nested_virtualization: true
        type: "n2-standard-2"
        scopes: ["cloud-platform"]
    matrix:
        - &base_image
          name: "${PACKER_BUILDS} Base Image"
          env:
            PACKER_BUILDS: "fedora"
        - <<: *base_image
          env:
            PACKER_BUILDS: "prior-fedora"
        - <<: *base_image
          env:
            PACKER_BUILDS: "ubuntu"
        - <<: *base_image
          env:
            PACKER_BUILDS: "prior-ubuntu"
    script: "ci/make_base_images.sh"
    manifest_artifacts:
        path: base_images/manifest.json
        type: application/json

task:
    alias: "cache_images"
    only_if: $CIRRUS_PR =~ '.+'
    depends_on:
        - base_images
    # Packer needs time to clean up partially created VM images
    auto_cancellation: $CI != "true"
    timeout_in: 40m
    container:
      dockerfile: "image_builder/Containerfile"
      cpu: 2
      memory: "2G"
    script: "ci/make_cache_images.sh"
    matrix:
        - &cache_image
          name: "${PACKER_BUILDS} Cache Image"
          env:
            PACKER_BUILDS: "fedora"
        - <<: *cache_image
          env:
            PACKER_BUILDS: "prior-fedora"
        - <<: *cache_image
          env:
            PACKER_BUILDS: "ubuntu"
        - <<: *cache_image
          env:
            PACKER_BUILDS: "prior-ubuntu"
    manifest_artifacts:
        path: cache_images/manifest.json
        type: application/json

task:
    name: &success_name success
    alias: *success_name
    depends_on:
        - validate
        - image_builder
        - podman_containers
        - base_images
        - cache_images
    container:
        <<: *ci_container
    clone_script: mkdir -p "${CIRRUS_WORKING_DIR}"  # source is not needed
    script: /bin/true
